DO-1298 upload conquest python to proget

diff --git a/.github/workflows/build-conquest-python.yml b/.github/workflows/build-conquest-python.yml
--- a/.github/workflows/build-conquest-python.yml
+++ b/.github/workflows/build-conquest-python.yml
@@ -9,7 +9,8 @@ on:  # yamllint disable-line rule:truthy
         default: false
         type: boolean
       platforms:
-        description: 'Platform to build for, eg. '
+        description: "Platform to build for"
+        type: choice
         options:
           - 'rocky8'
           - 'ubuntu'
@@ -31,7 +32,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Set output
         id: set_output
@@ -64,7 +65,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -118,3 +119,28 @@ jobs:
           jfrog rt upload --flat \
             "${{ env.archive_path }}/${{ env.archive_filename }}" \
             "ccdc-3rdparty-python-interpreters/conquest_python/2.7/"
+
+      - name: Upload conquest python to ProGet
+        if: ${{ inputs.artifactory-push }}
+        shell: bash
+        env:
+          PROGET_API_KEY: ${{ secrets.PROGET_API_KEY }}
+          PROGET_BASE_URL: ${{ vars.PROGET_BASE_URL }}
+          PROGET_ASSET_DIRECTORY: ${{ vars.PROGET_ASSET_DIRECTORY }}
+        run: |
+          PROGET_ENDPOINT="${PROGET_BASE_URL}/endpoints/${PROGET_ASSET_DIRECTORY}/content/conquest_python/2.7/${{ env.archive_filename }}"
+
+          curl -X POST \
+            -H "Content-Type: application/octet-stream" \
+            -H "X-ApiKey: ${PROGET_API_KEY}" \
+            --data-binary "@${{ env.archive_path }}/${{ env.archive_filename }}" \
+            --fail-with-body \
+            "$PROGET_ENDPOINT"
+
+          if [ $? -eq 0 ]; then
+            echo "Successfully uploaded ${{ env.archive_filename }} to ProGet"
+          else
+            echo "Failed to upload ${{ env.archive_filename }} to ProGet"
+            exit 1
+          fi
+
